print("Funcionalidad para ingreso de Usuarios")
print("Funcionalidad para ingreso de Empleados")
print("Funcionalidad para ingreso de contratistas")
print("Funcionalidad para ingreso de Funcionarios")
print("Funcionalidad para ingreso de Jefes")
