import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}

pipeline {
  agent any   // o: agent { label 'windows' } si tienes ese label

  environment {
    appName = "variable"
  }

  stages {
    stage("paso 1") {
      steps {
        script {
          bat 'echo hola mundo'
        }
      }
    }
  }

  post {
    always {
      deleteDir()
      bat 'echo fase always'
    }
    success {
      bat 'echo fase success'
    }
    failure {
      bat 'echo fase failure'
    }
  }
}
